CREATE DATABASE Snake_Game
GO

USE Snake_Game
GO

CREATE TABLE Jugadores (
id INT PRIMARY KEY IDENTITY(1,1),
Nombre VARCHAR(100) NOT NULL,
Pseudonimo VARCHAR(100) UNIQUE NOT NULL,
fecha_registro DATETIME DEFAULT GETDATE()
);

CREATE TABLE Partidas (
id INT PRIMARY KEY IDENTITY(1,1),
id_jugador INT FOREIGN KEY REFERENCES Jugadores(id),
fecha_inicio DATETIME NOT NULL,
fecha_fin DATETIME NOT NULL,
puntaje INT NOT NULL
);

SELECT * FROM Jugadores
SELECT * FROM Partidas